### ISSUE TITLE
[Bug]: Missing picocolors

### ISSUE THREAD

**Issue by fi3ework** [web-infra-dev/rsbuild#2829]
### Version

```sh
v1.0.0-alpha.5
```

### Details

When bumping Rsbuild to v1.0.0-alpha.5 in https://github.com/rspack-contrib/storybook-rsbuild. I encounter this issue

```txt
 p storybook

> @sandboxes/react-rsbuild@0.0.0 storybook /Users/bytedance/Projects/storybook-rsbuild/sandboxes/react-rsbuild
> storybook dev -p 6006

@storybook/cli v8.1.1

info => Starting manager..
info => Starting preview..
info Addon-docs: using MDX3
=> Failed to build the preview
Error: Cannot find module 'picocolors'
Require stack:
- /Users/bytedance/Projects/storybook-rsbuild/node_modules/.pnpm/@rsbuild+core@1.0.0-alpha.5/node_modules/@rsbuild/core/compiled/autoprefixer/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._resolveFilename (/Users/bytedance/Projects/storybook-rsbuild/node_modules/.pnpm/esbuild-register@3.5.0_esbuild@0.20.2/node_modules/esbuild-register/dist/node.js:4799:36)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at 146 (/Users/bytedance/Projects/storybook-rsbuild/node_modules/.pnpm/@rsbuild+core@1.0.0-alpha.5/node_modules/@rsbuild/core/compiled/autoprefixer/index.js:9250:18)
    at __nccwpck_require__ (/Users/bytedance/Projects/storybook-rsbuild/node_modules/.pnpm/@rsbuild+core@1.0.0-alpha.5/node_modules/@rsbuild/core/compiled/autoprefixer/index.js:10193:43)
    at 9210 (/Users/bytedance/Projects/storybook-rsbuild/node_modules/.pnpm/@rsbuild+core@1.0.0-alpha.5/node_modules/@rsbuild/core/compiled/autoprefixer/index.js:1186:12)
    at __nccwpck_require__ (/Users/bytedance/Projects/storybook-rsbuild/node_modules/.pnpm/@rsbuild+core@1.0.0-alpha.5/node_modules/@rsbuild/core/compiled/autoprefixer/index.js:10193:43)
    at /Users/bytedance/Projects/storybook-rsbuild/node_modules/.pnpm/@rsbuild+core@1.0.0-alpha.5/node_modules/@rsbuild/core/compiled/autoprefixer/index.js:10213:37

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

The prebundled picocolors is removed in this line https://github.com/web-infra-dev/rsbuild/pull/2798/files#diff-ba85075ab9769f37b2568bda1162bbd314b75cf883121b3ff2487249f3dfe362L82.

It should be prebunled, if we want to reuse the prebundled picocolors for more than one other prebundled packages, we need to prebundle it to

```
-compiled
   - node_modules
      - picocolor
   - autoprefixer
   - other_prebundled_packages_deps_on_picocolors
```

However, https://www.npmjs.com/package/prebundle does not support prebundled distPath (https://github.com/rspack-contrib/prebundle/blob/f8ac2440da513a3d8920e81e495d1f43aea27839/src/helper.ts#L40). Should that be the proper solution?

### Reproduce link

/

### Reproduce Steps

Go to https://github.com/rspack-contrib/storybook-rsbuild, bump @rsbuild/core, start a sandbox.

**Comment by fi3ework** [comment]
It's prone to occur in a hoist disabled monorepo.

**Comment by chenjiahan** [comment]
My mistake, I will fix that
